# fly.toml app configuration file generated for shidou on 2024-03-18T21:17:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shidou'
primary_region = 'ord'

[build]

[env]
  LIBSQL_LOCAL_DB_PATH = 'file:local_replica.db'
  RUST_LOG = 'shidou=debug'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '30s'
    timeout = '10s'
    grace_period = '1m0s'
    method = 'get'
    path = '/healthcheck'

[[vm]]
  size = 'shared-cpu-1x'
